### ISSUE TITLE
Efilm 2.1.2 seems to seen funny presentation contexts, break on PDU.read

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom-samples#2]
In PDU.read, there are two lines like this:

```
 var pc =
      _assoc.PresentationContexts.SingleOrDefault(
             context => context.AbstractSyntax.UID.Equals(syntax));
```

I was testing a vanilla STORESCP (from the examples) in 3.0 beta and it was throwing errors because Efilm 2.1.2 seems to send proposed presentation contexts with duplicate transfer syntaxes.

I fixed it by using FirstOrDefault instead.

**Comment by anders9ustafsson** [comment]
@aerik Sorry for the late follow-up, but this is really a *fo-dicom* issue rather than a samples issue, right?

**Comment by anders9ustafsson** [comment]
Since this issue needs to be solved in the *fo-dicom* code base, the issue has been moved [there](https://github.com/fo-dicom/fo-dicom/issues/391).
