### ISSUE TITLE
How do I use fo-dicom to get http://www.dicomserver.co.uk/ files through c-move?

### ISSUE THREAD

**Issue by pengxiaobo123** [fo-dicom/fo-dicom-samples#24]
hello.
        How can I write to get the information returned to http://www.dicomserver.co.uk/ website through c-move? I can send c-move commands by checking simple, but I can't get any files returned.

thank you
pengxiaobo

**Comment by gofal** [comment]
C-move is somehow difficult on public servers. 
C-Get is like a HTTP-Get: you create an association and request an image and the server returns the image in the same connection.
C-Move on the other side is decoupled: you create an association to the public server and send a move request like "send study with UID 1.2.3.455 to AET workstation1". then the server has to know the network connection of "workstation1" and creates a new association to workstation1 and sends the images. While it is simple through your firewall and proxy to reach www.dicomserver.co.uk it is very likely that the dicomserver is not able to connect to your machine. 

Medical connections writes this on their website of www.dicomserver.co.uk: 

> "The C-MOVE support is unusual, as most DICOM servers can only work if the C-MOVE destination has been preprogrammed into them, as the DICOM protocol requires the destination AE title to be translated into an IP address and port number. This server can use a predefined list (set up by the administrator), but in addition, if an AET is not in the “known” list, then and if it is the same as the requesting AET, then the server assumes that there is a listener at the originating IP address on the same port used to access the server (normally 104 or 11112). This will work for most cases, but if you need something different set up, please let me know (this will require both an addition to the database, and a firewall relaxation)."

Are you really sure that your machine is accessible from the internet side?

**Comment by pengxiaobo123** [comment]
Sorry, I later found out that my computer was in the internal network, and that I couldn't directly access my computer. Later, I used a computer with a public net IP to get the information back.
