### ISSUE TITLE
Refused: SOP class not supported(Help Wanted)

### ISSUE THREAD

**Issue by AhmetAymed** [fo-dicom/fo-dicom-samples#26]
I have tested newly Query Scu Example. I have a worklist server run on my pc on port 105. I'm testing it several dicom sdks like fo-dicom. But here ı have a problem with SOP class. 
With a different request of roniza dicom sdk makes successful query with its sop class uid of : 
http://prntscr.com/jn1iie
http://prntscr.com/jn1g80
So, what is the problem here with SOP classes ?

**Comment by gofal** [comment]
You are using the QR SCU example. This example is intended to query images from a PACS archive, not for querying a RIS/HIS worklist.
the C-Find request is very similar if you want to search for available images or for available scheduled procedures. The difference is the type - the sopclass.

For doing a worklist query, do the following:

```
var cfind = DicomCFindRequest.CreateWorklistQuery(); // add here optional filter-parameters
cfind.OnResponseReceived = (DicomCFindRequest rq, DicomCFindResponse rp) => {
	Console.WriteLine("Study UID: {0}", rp.Dataset.Get<string>(DicomTag.StudyInstanceUID));
};

var client = new DicomClient();
client.AddRequest(cfind);
client.Send("127.0.0.1", 11112, false, "SCU-AE", "SCP-AE");


```

**Comment by gofal** [comment]
Meanwhile there is also a small sample application showing a worklist query:
https://github.com/fo-dicom/fo-dicom-samples/tree/master/Desktop/Worklist%20SCU.

Is your code now working? Any issue still open?
