### ISSUE TITLE
CMove and CGet examples

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom-samples#3]
_Originally posted as fo-dicom/fo-dicom#345 by user @Ravenheart:_

I would really benefit if there was a CMove SCP and CGet SCP example available. I've found only one example here [fo-dicom google groups](https://groups.google.com/forum/#!topic/fo-dicom/ic35XVDD1Hc) but that implementation is very slow in sending the images. DicomClient sends one picture, disconnects and then reconnects and sends one picture again, lots of time is lost between association and deassociation.

**Comment by CelerityAbbottPC** [comment]
Is there a fo-dicom query / retrieve example available?

**Comment by CelerityAbbottPC** [comment]
For dcmtk, there looked some Q/R samples:

OFFIS DCMTK: dcmqrscp: DICOM image archive (central test node)
http://support.dcmtk.org/docs/dcmqrscp.html

OFFIS DCMTK: movescu: DICOM retrieve (C-MOVE) SCU
http://support.dcmtk.org/docs/movescu.html
The movescu application implements both an SCU for the Query/Retrieve Service Class and an SCP for the Storage Service Class.

OFFIS DCMTK: findscu: DICOM query (C-FIND) SCU
http://support.dcmtk.org/docs/findscu.html
It sends query keys to an SCP and awaits responses. The application can be used to test SCPs of the Query/Retrieve and Basic Worklist Management Service ...

DCMTK: getscu: DICOM retrieve (C-GET) SCU
http://support.dcmtk.org/docs-dcmrt/getscu.html
It sends query keys to an SCP and waits for responses with images or other DICOM objects sent via C-STORE. As the DICOM service demands, C-GET and the ...

It'd be great and very useful if fo-dicom experts could put together samples similar to dcmtk's.  It'd be very helpful to have more developers use fo-dicom.
