### ISSUE TITLE
Missing Methods in dicomdataset

### ISSUE THREAD

**Issue by mas74** [fo-dicom/fo-dicom-samples#31]
Hello

I try to implement a cGet or cMove from the provided Exampls Queryretrieve SCU but i do not have the method ' GetSingleValue' in the DicomDataset.

I am using fo-Dicom.Desktop V 3.0.2 from nuget. with .Net 4.5.2
The nuget Package added the refence Dicom.Core to my Project.

What is missing or wrong?

![30-08-_2018_11-16-12](https://user-images.githubusercontent.com/42672751/44842462-71f62100-ac35-11e8-8d52-0fd6d9d2a393.png)

Thank you for your help and Regards, Marc

**Comment by gofal** [comment]
sorry for the delayed answer.
The samples are built using fo-dicom version 4.0.0-rc1. With nuget also include prelease versions to see it.
