### ISSUE TITLE
Issues with Getting Response from C-find with Orthnac Server

### ISSUE THREAD

**Issue by deepakaneja** [fo-dicom/fo-dicom-samples#32]
#26 Hello All,

I am using the fo-dicom for imaging device,

when i am trying to getting response from c-find function at the time Refused: Sop class is not supported failure message are showing . can any one can help for related this issue.

`private void CFind()
{
try
{
var cFind = DicomCFindRequest.CreateWorklistQuery();
var client = new DicomClient();
cFind.OnResponseReceived = (DicomCFindRequest request, DicomCFindResponse response)=>
{
if (response.HasDataset)
{
var instance = response.Dataset.Get(Dicom.DicomTag.SOPClassUID);
}
};
client.NegotiateAsyncOps();
client.AddRequest(cFind);
client.Send("192.168.0.66", 4242, false, "ORTHANC", "ORTHANC");

        }
        catch (Exception ex)
        {
        }
    }`
Showing this message and get dataset is null.
![screenshot_10](https://user-images.githubusercontent.com/11642849/46202250-e9ea6080-c333-11e8-82bf-4351021df40c.png)

This is the .dcm file whic is used

![screenshot_9](https://user-images.githubusercontent.com/11642849/46202274-fbcc0380-c333-11e8-90f7-a2aef05690e5.png)

**Comment by gofal** [comment]
Hi, you are sending the wrong query. A worklist c-find has its own sop class uid. it is intended to get a list of patients who are planned for an examination.
to ask for already archived images, create a Study-, patient- or series-Query.

**Comment by gofal** [comment]
Will close this issue. If there are still problems, feel free to reopen this issue.
