### ISSUE TITLE
PrintServices.cs returns wrong UID during print job

### ISSUE THREAD

**Issue by auspaco** [fo-dicom/fo-dicom-samples#33]
When receiving files from an us machine, it would abort directly after printing the first image. Looking at the code in PrintServices.cs line 599

` response.Command.AddOrUpdate(DicomTag.AffectedSOPInstanceUID, printJob.SOPInstanceUID);`

Replacing printJob with request works perfectly -  as per the dicom standard it should be the request UID returned.

I'm not sure if this fixes some of the other outstanding issues or not, but it may.

**Comment by gofal** [comment]
Thanks for showing a solution. You'd like to create a pull request or shall I?
