### ISSUE TITLE
Print SCU association rejected

### ISSUE THREAD

**Issue by Jarekw69** [fo-dicom/fo-dicom-samples#34]
Hello, I am using foDicom 4.0.1/Print SCU. My Dicom printer rejects association. The following is the log:
//-------------------------------------------------------------------
[...cut ...]
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Basic Film Session SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Basic Film Box SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Basic Grayscale Image Box SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
2019-04-17 09:31:52.7701 BBBBBBBB<- Association reject [result: Permanent; source: ServiceUser; reason: NoReasonGiven]
2019-04-17 09:31:52.7701 Connection closed
//-------------------------------------------------------------------------------
The dicom conformance statement of the printer says it supports: Basic Grayscale Print Management Meta SOP Class  (1.2.840.10008.5.1.1. 9) which 'contains' the 3 SOP Classes negotiated explicitly by foDicom client, The printer allows only implicit negotiation of the 3  SOP Classes on meta level (i.e. only one Meta SOP class schould be negotiated).  Is there a way to tell foDicom client to negotiate on meta level?  Thank you very much.
Jarek

**Comment by hdesouky** [comment]
What is the model of the printer? can you share the conformance statement?

**Comment by Jarekw69** [comment]
The printer is Codonics Horizon. I checked out the conformance statement and, to make things short, it says the printer will not negotiate each of the SOP Classes explicitly - only the meta class can be negotiated, with implicit accept for all the 'sub' SOP classes. The only exception is Printer SOP Class (also a part of the Basic Grayscale Print Management Meta SOP Class) that can be negotiated separately. Having analyzed foDiom source I have come to the conclusion that at least two methods schould be customized to allow meta level negotiation: AddFromRequest and PostMessageAsync (these might be misspelled sorry about that I dont have the code now before my eyes).

**Comment by hdesouky** [comment]
Check the below code snippet:
`            if (!Color)
            {
                Log.Information("ADDING GRAY SCALE PRINT SOP");
                var pc = new DicomPresentationContext(0, DicomUID.BasicGrayscalePrintManagementMetaSOPClass);
                pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
                dicomClient.AdditionalPresentationContexts.Add(pc);
            }
            else
            {
                Log.Information("ADDING COLOR PRINT SOP");
                var pc = new DicomPresentationContext(0, DicomUID.BasicColorPrintManagementMetaSOPClass);
                pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
                dicomClient.AdditionalPresentationContexts.Add(pc);
            }`

**Comment by Jarekw69** [comment]
Thank you. I will give it a try, in the nearest days. My concern with this approach is however the following: when I add the additional PC it will be accpeted, but the other 3 rejected (as they also will be proposed) so they will not be in the association's PresentationContexts collection with Accepted flag. Then, when each of the 3 actual requests is about to be posted, foDicom will not find the PC related to each of them in the collection and throw an exception.  Schould foDicom somehow know that it is actually Basic Grayscale Print Management Meta SOP Class Abstract Syntax to be searched when sending a request with e.g. Basic Film Session SOP Class? But this is theory. Lets see what the printer says. Thanks for the suggestion!

**Comment by gofal** [comment]
This issue has been fixed in fo-dicom 4.0.3 (https://github.com/fo-dicom/fo-dicom/issues/667)
