### ISSUE TITLE
QueryRetrieve_SCU  throw Exception 

### ISSUE THREAD

**Issue by zhongx** [fo-dicom/fo-dicom-samples#40]
Run the QueryRetrieve_SCU  with your demo throws Exception 
at "var cGetRequest = CreateCGetBySeriesUID(studyUID, serieUids.First())"
Because the length of serieUids is 0.
I use the following config:
private static string StoragePath = @".\DICOM";
private static string QRServerHost = "www.dicomserver.co.uk"; 
private static int QRServerPort = 104; 
private static string QRServerAET = "STORESCP";
private static string AET = "FODICOMSCU";

pls help me!

**Comment by gofal** [comment]
Of course this code is just a sample. If seriesUids is an empty list, then the webserver did not return any seriesdata in the previous CFind request. 
www.dicomserver.co.uk is a public server and of course there the data may change. Please try other query parameters. And of course if you want to implement an real-world application you have to add some error check, like `if seriesUids.Any() { .... `.

**Comment by zhongx** [comment]
> Of course this code is just a sample. If seriesUids is an empty list, then the webserver did not return any seriesdata in the previous CFind request.
> [www.dicomserver.co.uk](http://www.dicomserver.co.uk) is a public server and of course there the data may change. Please try other query parameters. And of course if you want to implement an real-world application you have to add some error check, like `if seriesUids.Any() { .... `.

thank you for your patience and replies。
