### ISSUE TITLE
Private UIDs

### ISSUE THREAD

**Issue by phelys** [fo-dicom/fo-dicom-samples#43]
How to add private UIDs? error: 1.3.46.670589.33.1.4.1 is not a transfer syntax type. Please, some ideia?

**Comment by gofal** [comment]
See here: https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes#custom-transfer-syntaxes
You can register custom transfersyntaxes from version 4.0.1 on.

**Comment by gofal** [comment]
I will close this due to inactivity. Please feel free to reopen this issue if the issue still exists.
