### ISSUE TITLE
Dicom.Network.DicomAssociationRejectedException

### ISSUE THREAD

**Issue by shree2695** [fo-dicom/fo-dicom-samples#44]
Dear All,
We have encountered the following problem while sending the Dicom files to print using **SCU** print.

Dicom.Network.DicomAssociationRejectedException: Association rejected [result: Permanent; source: ServiceProviderPresentation; reason: 56]

Could you please tell us how to resolve it? 
Printer is Drypix

Thanks

**Comment by gofal** [comment]
I updated the sources to use fo-dicom version 4.0.3. In this version a bug concerning print associations was fixed (#667). Please use the latestest version from nuget and give it a try.

**Comment by gofal** [comment]
I will close this due to inactivity. Please feel free to reopen this issue if the issue still exists.
