### ISSUE TITLE
C-ECHO on web server then hang.

### ISSUE THREAD

**Issue by Potatof** [fo-dicom/fo-dicom-samples#47]
In test project DICOM.Desktop  - DICOM.Tests.Desktop :	

Dicom.Network.AsyncDicomCEchoProviderTests.OnCEchoRequestAsync_ShouldRespond
\AsyncDicomCEchoProviderTests.cs 

I've just change line 30
var client = new Network.Client.DicomClient("127.0.0.1", port, false, "SCU", "ANY-SCP")
by
var client = new Network.Client.DicomClient("www.google.com", 80, false, "SCU", "ANY-SCP")

Debug the test, and... loop indefinitely

How to manage Association Request retries ?

**Comment by gofal** [comment]
very creative test :-)

**Comment by gofal** [comment]
this seems to be a bug in fo-dicom itself, not in the samples implementation. therefore I "moved" this issue to the fo-dicom repository.
