### ISSUE TITLE
'IImage' does not contain a definition for 'Save' 

### ISSUE THREAD

**Issue by KevinFT** [fo-dicom/fo-dicom-samples#50]
Hi,  I am trying to convert Dicom to JPG image. I used sample code from this project. I am new to this. Please advise. Thank you in advance!

Code:
            var img= new DicomImage(@"ImageFileName00.dcm");
            img.RenderImage().Save(testDir + @"\test.jpg");

Error:
'IImage' does not contain a definition for 'Save' and no accessible extension method 'Save' accepting a first argument of type 'IImage' could be found (are you missing a using directive or an assembly reference?)

**Comment by gofal** [comment]
To save an image, it really depends on the implementation of IImage. IImage is a general interface and requires to have a implementation like System.Drawings GDI-based WinFormsImage, or ImageSharpImage, or WPF-based WindowsImage, ...

So you need to call `.As...()` before to convert the IImage into your implementation like System.Drawing.Bitmap or similar and then use their Save method.
Fo-dicom is about implementing DICOM-Standard, but not about image-handling, codec-handling or file-handling.

See here this sample on fo-dicom's main page:

https://github.com/fo-dicom/fo-dicom#render-image-to-jpeg

or this wiki page:

https://github.com/fo-dicom/fo-dicom/wiki/Image-rendering

**Comment by gofal** [comment]
I will close this due to inactivity. Please feel free to reopen this issue if the issue still exists.
