### ISSUE TITLE
Is there a Xamarin.Forms version?

### ISSUE THREAD

**Issue by anwarsayee49** [fo-dicom/fo-dicom-samples#53]
Is there a Xamarin.Forms version of fo-dicom? It would be very much more helpful if it is available.

**Comment by gofal** [comment]
fo-dicom is "only" a library for handling DICOM files and DICOM network communication. Additianly it also provides helper- and convenience classes for rendering, displaying etc. But it does not contain any UI. This project here only shows how you could possibly utilize fo-dicom for your application.

a search in github for "xamarin fo-dicom" listed the first result:
https://github.com/ukgraphics/xf-fo-dicom-sample
i did not take a close look, but you might try that?

**Comment by gofal** [comment]
I will close this due to inactivity. Please feel free to reopen this issue if the issue still exists.
