### ISSUE TITLE
 print scp how to get the patient's name

### ISSUE THREAD

**Issue by andersoncav** [fo-dicom/fo-dicom-samples#57]
good afternoon

please could you tell me how to get the patient's name from the scp print.
I need to save the pdf file the name of the patient

Path.Combine(FullPrintJobFolder, SOPInstanceUID.UID)

**Comment by gofal** [comment]
The patient's name is not contained in a PrintJob.
In DICOM the printjob is really intended to be printed on some printerdevice. So the content of a printjob are only the ready rendered pixels and a lot of information how to print these pixels (layout format, color of borders, backgroundcolor of the area where no pixeldata is provided etc). So you do have no chance to get the patient data savely. You could read the PixelData and do OCR (text recognition within an image), but I really would recommend not to do that.
