### ISSUE TITLE
Question | Image Resolution Print SCP

### ISSUE THREAD

**Issue by AhmedSamak101** [fo-dicom/fo-dicom-samples#6]
Hello Team, 
I am confused about the main factor of image resolution in Print SCP 
in the file PrintJob.cs is found the following parameter for _imageResolution_ with value _100_ 
```
   private void OnPrintPage(object sender, PrintPageEventArgs e)
        {
            _currentFilmBox.Print(e.Graphics, e.MarginBounds, 100);
.....
```
meanwhile, we have the entry _(2020,0050) RequestedResolutionID_  which can be "STANDARD" or "HIGH" ```
(2020,0050) CS [HIGH]                                           #     4, RequestedResolutionID
(2020,0050) CS [STANDARD]                                       #     8, RequestedResolutionID
```
Increasing the the parameter to 1200 results a better image but I still confused of what is the main factor of image resolution. I appreciate your advise or referral to a resource that can clear the issue up.
Thanks
Best regards,
Ahmed Samak

**Comment by hdesouky** [comment]
Hello Ahmed,

The image resolution you pass to the film box specify the resolution of generated images before sending them to the windows printer (the target graphics)

The Requested Resolution determine the resolution the client want the target printer using.

You can build your own internal map to fullfill the print request
Low will pring using 150dpi
Standard will print using 300 dpi
High will print using 600 dpi

Be aware that using resolution higher than 150 dpi actually will not offer any enhancement if your target print media is ordinary A4-A3 paper

Hope the above answer removes your confusion

**Comment by AhmedSamak101** [comment]
@hdesouky Thank you very much for your clarifications. 
frankly speaking? still partially confused :) 
Please have a look at the case below:
I send print jobs from ClearCanvase Workstation:

- setting _requested resolution_ to _High_ generates a PDF file _427KB_ 
- while sending the same job with _STANDARD_ generates _169KB_ 
- the targeted graphic is _100_ as is for both of them. 
there is some thing -unknown for me- influencing the image quality. 

I am going to perform a physical printing test I'll play with the parameters, read some more and back to you if I have further questions.

Best regards,
Ahmed Samak

**Comment by anders9ustafsson** [comment]
@AhmedSamak101 Any update on your success with this? I am closing the issue for now, please re-open it if you have remaining problems.

**Comment by iamps** [comment]
@AhmedSamak101
Could you resolve the image quality query. Please let me know, that will also help me.
Also let me know the link where you downloaded printscp code from.

Thanks
--

**Comment by AhmedSamak101** [comment]
Hello @iamps  
it wasn't an issue, I just was keen to know what is the factor that influences the image resolution, finally I made it configurable to the user to pass 100 to 1200 dpi to the param below:
`   private void OnPrintPage(object sender, PrintPageEventArgs e)
        {
            _currentFilmBox.Print(e.Graphics, e.MarginBounds, **100**);
..... `
If I understood your question about code, just clone or download the current repository 
https://github.com/fo-dicom/fo-dicom-samples/archive/master.zip

Best regards,
Ahmed Samak

**Comment by iamps** [comment]
Thanks Ahmed for the reply.

Please clear one more thing. Did you face the issue that when you send print jobs to the print scp sometime it starts printing the same old  job even if the new job is sent.


Thanks

Prakkash


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by AhmedSamak101** [comment]
@iamps No, I haven't ever seen this behavior before, but may I suggest 3 steps to figure-out what is going on? :)
- Isolate the printer, you can change to MS Print to PDF, Pullzip PDF or MS XPS  because there may be a problem with printer driver.
- Also, you may delete the Printed Job folder to ensure that your software will find nothing old to print. 
- Try to find out what is the status of the printed job at PSU Print Service User
Hope that help  
Best regards,
Ahmed Samak

**Comment by iamps** [comment]
Thanks for the tips.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by iamps** [comment]
Hi Ahmed
May I ask you for your email id.

**Comment by AhmedSamak101** [comment]
Hello Hesham,
My email is ahmedsamak1515@gmail.com

Best regards,
Ahmed Samak
