### ISSUE TITLE
 Scp print can't print Standard \ 2.3 could

### ISSUE THREAD

**Issue by andersoncav** [fo-dicom/fo-dicom-samples#60]
Scp print can't print Standard \ 2.3 could someone help me

**Comment by gofal** [comment]
The implementation of printing in fo-dicom is not feature-complete, but grid-printing is supported, so it should work.
First of all: the content should be "STANDARD\2,3", so upper case letters, no space, and a comma between the numbers.

Maybe you share your exact code you are using, then it is easier to help you.
