### ISSUE TITLE
Not able to compress dicom file

### ISSUE THREAD

**Issue by Dash-Uttam** [fo-dicom/fo-dicom-samples#73]
DicomDataset ds = new DicomDataset();
                        ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);
                        ds.Add(DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage);
                        if (StudyID.Any() && !string.IsNullOrEmpty(StudyID[0]))
                        {
                            ds.Add(DicomTag.StudyInstanceUID, StudyID[0]);
                            ds.Add(DicomTag.SeriesInstanceUID, SeriesId[0]);
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.PatientID, PID[0]);
                            ds.Add(DicomTag.AccessionNumber, AcnNumber[0]);
                        }
                        else
                        {
                            ds.Add(DicomTag.StudyInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.SeriesInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.PatientID, patientDetailsModelForDicom.PatientId);
                            ds.Add(DicomTag.AccessionNumber, patientDetailsModelForDicom.AccessionNumber);
                        }
                        ds.Add(DicomTag.PatientName, patientDetailsModelForDicom.PatientName);
                        ds.Add(DicomTag.PatientSex, patientDetailsModelForDicom.Gender);
                        ds.Add(DicomTag.PatientBirthDate, patientDetailsModelForDicom.PatientBirthDate);
                        ds.Add(DicomTag.StudyDate, DateTime.Now);
                        ds.Add(DicomTag.StudyTime, DateTime.Now);

                        DicomPixelData pixelData = DicomPixelData.Create(ds, true);
                        pixelData.BitsStored = 8;
                        pixelData.SamplesPerPixel = 3;
                        pixelData.HighBit = 7;
                        pixelData.PixelRepresentation = 0;
                        pixelData.PlanarConfiguration = 0;

                        int i = 0;
                        foreach (var files in model.Files)
                        {
                            Bitmap bitmap;
                            using (var ms = new MemoryStream(model.Files[i].Media))
                            {
                                bitmap = new Bitmap(ms);
                            }
                            byte[] pixels = GetPixels(bitmap);
                            MemoryByteBuffer buffer = new MemoryByteBuffer(pixels);
                            ds.AddOrUpdate(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
                            ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);
                            ds.AddOrUpdate(DicomTag.Rows, (ushort)bitmap.Height);
                            ds.AddOrUpdate(DicomTag.Columns, (ushort)bitmap.Width);
                            ds.AddOrUpdate(DicomTag.InstanceNumber, "1");

                            pixelData.AddFrame(buffer);
                            i++;
                        }

                        DicomDataset sqContent = new DicomDataset(); //Content of the sequence
                        sqContent.Add(DicomTag.Modality, "US");
                        sqContent.Add(DicomTag.ScheduledProcedureStepStartDate, DateTime.Now.Date);

                        DicomSequence sq = new DicomSequence(DicomTag.ScheduledProcedureStepSequence, sqContent); // Create sequence, add content
                        ds.AddOrUpdate(sq); //Add sequence to main dataset

                        DicomFile file = new DicomFile();
                        file.Dataset.Add(ds); //Add main dataset to DicomFile
                        

                        fileName = Path.Combine(DicomFolderPath, "001" + ".dcm");
                        file.FileMetaInfo.TransferSyntax = DicomTransferSyntax.ImplicitVRLittleEndian; //Specify transfer syntax
                        file.Save(fileName); //Save file to disk

                        await client.AddRequestAsync(new DicomCStoreRequest(fileName));
                        await client.SendAsync();

Above will create multiimage dicom file successfully. but it's size is too big, I am using 3500-4000 frames and it goes in 2 gb dicom files. Apart from that when i create single image dicom file from 1 jpeg, it will create 37 mb dicom file for only single jpeg image, the jpeg file is only 127 kb. 

Please help me into that.

**Comment by gofal** [comment]
Dicom is per default a file format with uncompressed pixel data, comparable with the old .bmp Bitmap.
But of course there are also compressions available. Those are implemented in a separate nuget package *fo-dicom.codecs* by Efferent-Health.
See the fo-dicom github main page for a code sample. You can configure to use the codec. And then, before saving the file, just call

    file = file.Clone(TransferSyntax.JPEGProcess1);

or

    file = file.Clone(TransferSyntax.JPEGProcess14);

or whatever compression you prefer.
