### ISSUE TITLE
Real time data

### ISSUE THREAD

**Issue by rubenmonteiro** [fo-dicom/fo-dicom-samples#90]
Hi all.
Is there any sample or test that I can use as a guideline to process/study data in real time.
I'm currently able to get studies from a DICOM server but is there a way to get data of a study that is currently being done.
I don't if I made my self clear.
Thanks for the help.

**Comment by gofal** [comment]
i do not know of any DICOM-standard way. It's the job of the DICOM-server to forward all incomming data immediatelly to a list of configured nodes. This routing is a main feature of all common DICOM archives.
The alternative if you do have query-acess, that you are polling the archive all the time. but this will propably reduce the performance of the archive.
You should contact the administrator of the DICOM server

**Comment by rubenmonteiro** [comment]
Thanks for the reply. I am still learning about the standard.
Using the dicom client class how can I configure on the server as a client node.

**Comment by gofal** [comment]
You cannot do a Server configuration as a Client. You have to ask someone who is able or allowed to do the configuration on the server.

**Comment by rubenmonteiro** [comment]
Thanks for the reply.
I didn't explain it correctly.
I'm currently developing a client using the examples and the package of the repository.
I can communicate with a dicom server, but I use long polling to fetch recent studies.
Using what you said, and if I understand, I need to configure my client as a node on the server, right?
This way I will get the latest studies added to the server.

**Comment by s004183** [comment]
Hi,
No polling to fetch, configure the PACS to notify your client when new instances has arrived.

Check [Instance Availability Notification Module](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.4.23.html)

I use this to receive new instances of studies stored in our PACS. FO-DICOM can implement easy a client to receive notification from the PACS. Yes, you must exists as a node in your PACS and must be subscribed to the IAN service of the PACS to receive notifications.

**Comment by rubenmonteiro** [comment]
Hi.
Thanks for the reply
