### ISSUE TITLE
Missing DICOM Tag for SyntheticData (0x0008, 0x001C)

### ISSUE THREAD

**Issue by Jordan-smit** [fo-dicom/fo-dicom-samples#95]
Hey,

I've noticed that the DICOM tag for SyntheticData (0x0008, 0x001C) is missing from the library's default dictionary. I have added it to my custom DICONDE dictionary so its not a major problem. However it would be great if this tag could be added to the default dictionary. Or if anyone knows if there is a reason it's currently omitted.

Thanks for any help!

![image](https://github.com/fo-dicom/fo-dicom-samples/assets/161819140/e9a37f27-922f-491e-a7ed-b60fd80580b0)

**Comment by mrbean-bremen** [comment]
The DICOM dictionary currently used in f-dicom is 2023b, while this tag has been only added in the latest standard (2024b), so it actually cannot be in the released version.
The DICOM dictionary is usually updated before a release.

**Comment by Jordan-smit** [comment]
I see! Thanks for the help.
